commands:
  install: nix develop -c true
  build: nix develop -c dune build
  test: nix develop -c dune runtest
  lint: nix develop -c dune build @fmt
  typecheck: nix develop -c dune build
  cli_version: nix develop -c dune exec rgoc -- --version

services: {}
